config/routes.rb
Rails.application.routes.draw do
  
  devise_for :professors

 resources :notifications do
  	member do
 	put "like", to: "notifications#upvote"
 	end
 end

  
  root 'notifications#index'
  
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	

	acts_as_votable
	belongs_to :professor

	has_attached_file :image, 
	styles: { medium: "300x300>",thumb: "100x100>"},
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml")
	
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :notifications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	
	before_action :find_notification, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_professor!, except: [:index, :show]
	def index
		@notifications = Notification.all.order("created_at DESC")
	end
	def show

		
	end
	def new
		@notification = current_professor.notifications.build

	end
	def create
		@notification = current_professor.notifications.build(notification_params)
		if @notification.save
			redirect_to @notification, notice: "Successfully Created!"
		else
			render 'new'
		end
	end
	def edit
		
	end
	def update
		if @notification.update(notification_params)
			redirect_to @notification, notice: "Successfully Updated"

		else
			render 'edit'
		end
	end
	def destroy
		@notification.destroy
		redirect_to root_path
	end
	def upvote
		@notification.upvote_by current_professor
		redirect_to :back
	end

	private
	def notification_params
		params.require(:notification).permit(:title, :description, :image)
	end
	def find_notification
		@notification = Notification.find(params[:id])
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.haml
!!! 5 
%html
%head
	%title Notify
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags 
	
%body
	%navbar.transparent
		%navbar-inner
			.container
				.navbar-brand
					%h1= link_to "Notify", root_path
				- if professor_signed_in?
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "New Notification", new_notification_path
					
						%li= link_to "Sign Out", destroy_professor_session_path, method: :delete
				- else 
					%ul.nav.navbar-nav.navbar-right
						%li= link_to "Sign up", root_path, data: {confirm: "This feature is coming soon!"}
						%li= link_to "Sign In", new_professor_session_path
		.container
			- flash.each do |name, msg|
				= content_tag :div, msg, class: "alert alert-info"
	= yield

app/views/notifications/_form.html.haml
= simple_form_for @notification, html: {multipart: true} do |f|
	- if @notification.errors.any?
		#errors
			%h2
			= pluralize(@notification.errors.count, "error")
			prevented this Notification from Saving!
			%ul
				- @notification.errors.full_messages.each do |msg|
					%li= msg 
	.form-group
		= f.input :image, input_html: {class: 'form-control'}

	.form-group
		= f.input :title, input_html: {class: 'form-control'}
	.form-group
		= f.input :description, input_html: {class: 'form-control'}
	= f.button :submit, class: "btn btn-primary"

app/views/notifications/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Edit Notification
	= image_tag @notification.image.url(:medium)
	= render 'form' 
	= link_to "Cancel", notification_path

app/views/notifications/index.html.haml
- require "paperclip-dropbox"
#notifications.transitions-enabled
	- @notifications.each do |notification|
		.box.panel.panel-default
			= link_to (image_tag notification.image.url), notification 
			.panel-body
				%h2= link_to notification.title, notification
				%p.professor 
				Submitted by
				= notification.professor.email

app/views/notifications/new.html.haml
.col-md-6.col-md-offset-3

	%h1 New Form
	= render 'form'

	= link_to "Back", root_path

app/views/notifications/show.html.haml
#notification_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.notification_image
				= image_tag @notification.image.url
			.panel-body
				%h1= @notification.title
				%p.description= @notification.description
				%p
			.panel-footer
				.row
					.col-md-6
						%p.professor
						Submitted by
						= @notification.professor.email
					.col-md-6
						.btn-group.pull-right
							= link_to like_notification_path(@notification),method: :put, class: 'btn btn-default' do
								%span.glyphicon.glyphicon-bell
								= @notification.get_upvotes.size
							= link_to "Back", root_path, class: 'btn btn-default'
							- if professor_signed_in?
								= link_to "Edit", edit_notification_path, class: 'btn btn-default'
								= link_to "Delete", notification_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default'